TXBridge/demo/demo-test/pom.xml, TXBridge/wsat-jta-multi_hop/pom.xml, TXBridge/wsat-jta-multi_service/pom.xml, XTS/demo/test/pom.xml
From time of 6.3.0.GA jboss Webservices are not able to start with address defined with square brackets (eg [::1]). In fact such specification of ip address is incorrect by spec. You should use just ::1.
The square brackets could be used just in url.
The result is that quickstarts does not work for EAP 6.3.0.GA when running on IPv6.
=> Changing node0 ipv6 address from [::1] to ::1 as does not work from 6.3.0.GA - see bz#1064771

spring/narayana-spring-boot/src/test/java/org/jboss/narayana/quickstart/spring/QuickstartApplicationTests.java
https://issues.jboss.org/browse/JBTM-2726
=> [JBTM-2726] Replace deprecated OutputCapture in Spring Boot quickstart test

build.bat
https://issues.jboss.org/browse/JBTM-2816
=> JBTM-2816 Quickstart can not find the mvn.bat after upgrade to maven 3.3.9

rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripCheck.java, rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripController.java, rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripService.java
https://issues.jboss.org/browse/JBTM-2947
Fixes a spec change where the quickstart was relying on the close call to return participant data. I changed it to interrogate each composite booking in order to arrive at the final trip booking status.
Requires jbosstm/narayana#1232
=> JBTM-2946 LRA specification compliance

XTS/wsat-jta-multi_service/pom.xml, XTS/wsat-jta-multi_service/src/test/java/org/jboss/narayana/quickstarts/wsat/jtabridge/fromjta/BridgeFromJTATest.java, XTS/wsat-jta-multi_service/src/test/java/org/jboss/narayana/quickstarts/wsat/jtabridge/fromjta/SecondClient.java, XTS/wsat-jta-multi_service/src/test/resources/arquillian.xml
for checking customer case CASE#01952249 there is change to set up
arquillian to use two containers to run the wsat mutli quicstart
the first container contains the tests and starts the runtime from it
the second only receives the XTS calls and joins the transaction by that
=> Changes to run wsat multi quickstart on two containers

transactionaldriver/transactionaldriver-standalone/pom.xml, transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/recovery/Ds1XAResourceRecovery.java, transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/recovery/RecoverySetupUtil.java, transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/util/DBUtils.java, transactionaldriver/transactionaldriver-standalone/src/main/resources/jbossts-properties.xml, transactionaldriver/transactionaldriver-standalone/src/test/java/io/narayana/TransactionalDriverTest.java
For the transactiona-driver-standalone quickstart cleaning the recovery
functionality and adding a simple XAResourceRecovery class
for further presentation.
Follow-up to https://github.com/jbosstm/quickstart/pull/217
This should be followed by another blog post about transactional driver (as preivous one https://jbossts.blogspot.cz/2017/12/narayana-jdbc-transactional-driver.html) and recovery.
=> Showcase of using transactional driver - recovery additions

.gitignore, ArjunaJTS/interop/glassfish/step1.sh, rts/at/jta-service/jpa/src/main/resources/META-INF/persistence.xml, rts/at/jta-service/jpa/src/main/webapp/WEB-INF/test-ds.xml, scripts/hudson/quickstart.sh
* fixing lra branch name to get the quickstart built
* using maven and wget non-interactive mode (`-B`) for not printing processing while downloading artifacts
* using WFLY nightly build not a static WFLY version defined in the script
* get built the wildfly in interop directory for testing with glassfish (see https://github.com/jbosstm/narayana/pull/1322)
=> [SCRIPT ONLY] get build lra plus using wfly nightly build

.gitignore, rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/FlightParticipant.java, rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/FlightService.java, rts/lra/hotel-service/src/main/java/io/narayana/rts/lra/demo/hotel/HotelParticipant.java, rts/lra/run.sh, rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripController.java, rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripService.java, scripts/hudson/quickstart.sh
https://issues.jboss.org/browse/JBTM-3027
Quickstart build stabilization.
This PR depends on the Narayana change being merged:
https://github.com/jbosstm/narayana/pull/1326
=> [JBTM-3027] changing dependencies from lra-annotations to lra eclipse ones

wildfly/commit-markable-resource/README.adoc
This is (only) addition of link to blogpost about CMR to cmr quickstart README.adoc.
=> Commit markable resource quickstart: adding link to blogpost

ArjunaJTS/interop/glassfish/step1.sh, XTS/ssl/xts-over-ssh.sh, scripts/hudson/quickstart.sh
Foreign repositories needs to be cloned for showing the integration with other projects. But we normally do not need whole git history and only the top-level layer is fine for us.
=> Reducing size of git clone for foreign repositories

XTS/ssl/pom.xml, XTS/ssl/xts-over-ssh.sh, XTS/wsat-jta-multi_service/pom.xml, blacktie/integration1/run.sh, blacktie/jatmibroker-xatmi/mdb-xatmi-service/run.sh, scripts/hudson/quickstart.sh
https://issues.jboss.org/browse/JBTM-3069
Fix for the XTS quickstarts over ssl. The quickstart itself is taken from WFLY quickstart repo and then adjusted to run with SSL. There was change on using bom in snapshot version in the WFLY repo and it was needed to accomodate with that fact.
On top of the fix there are serveral more changes which should ensure less space is used during running the quickstarts. There are added cleaning mechanism in the scripts and maven. And for the XTS/ssl the WildFly is not copied to two instances at all and both servers are run from the same location only data dirs are specific for each instance. This should hopefully help for https://github.com/jbosstm/quickstart/pull/235 to be successfully run.
=> [JBTM-3069] Fix for XTS ssl failure

LICENSE.md, rts/lra-examples/README.md, rts/lra-examples/api-participant-with-coordinator/README.md, rts/lra-examples/api-participant-with-coordinator/pom.xml, rts/lra-examples/api-participant/README.md, rts/lra-examples/api-participant/pom.xml, rts/lra-examples/api-participant/src/main/java/io/narayana/rts/lra/JaxRsActivator.java, rts/lra-examples/api-participant/src/main/java/io/narayana/rts/lra/ParticipantDeserializer.java, rts/lra-examples/api-participant/src/main/java/io/narayana/rts/lra/ProxyBasedResource.java, rts/lra-examples/api-participant/src/main/java/io/narayana/rts/lra/StateHolder.java, rts/lra-examples/api-participant/src/main/resources/META-INF/beans.xml, rts/lra-examples/cdi-participant-with-coordinator/README.md, rts/lra-examples/cdi-participant-with-coordinator/pom.xml, rts/lra-examples/cdi-participant-with-coordinator/run.sh, rts/lra-examples/cdi-participant/README.md, rts/lra-examples/cdi-participant/pom.xml, rts/lra-examples/cdi-participant/src/main/java/io/narayana/rts/lra/CdiBasedResource.java, rts/lra-examples/cdi-participant/src/main/java/io/narayana/rts/lra/JaxRsActivator.java, rts/lra-examples/cdi-participant/src/main/java/io/narayana/rts/lra/StateHolder.java, rts/lra-examples/cdi-participant/src/main/resources/META-INF/beans.xml, rts/lra-examples/lra-coordinator/README.md, rts/lra-examples/lra-coordinator/pom.xml, rts/lra-examples/mixed-participant-with-coordinator/README.md, rts/lra-examples/mixed-participant-with-coordinator/pom.xml, rts/lra-examples/mixed-participant-with-coordinator/src/main/java/io/narayana/rts/lra/MixedResource.java, rts/lra-examples/mixed-participant-with-coordinator/src/main/java/io/narayana/rts/lra/StateHolder.java, rts/lra-examples/pom.xml, rts/lra-examples/run.sh, rts/pom.xml
https://issues.jboss.org/browse/JBTM-3063
Did rely on jbosstm/narayana#1372 which has now been merged
Notes for the reviewer:
The code could probably do with more comments.
The quickstarts use thorntail uber jars.
1) The quickstart sets out a minimal pom and JAX-RS participant (cdi-participant). 
The pom depends on the lra implementation (lra-filters) and MP LRA api spec jar (microprofile-lra).
The servicve is a JAX-RS resource which counts the number of completion callbacks and it contains
- a method annotated with `@LRA(...)` to control the start and closing of the LRA
- methods annotated with `@Complete` and `@Compensate` to control LRA membership which both count the number of
completion/compensation callbacks
2) I then attempt to show how to achieve the same behaviour without CDI (ie …
=> JBTM-3063 LRA examples

rts/lra-examples/api-participant-with-coordinator/pom.xml, rts/lra-examples/api-participant/pom.xml, rts/lra-examples/api-participant/src/main/java/io/narayana/rts/lra/ParticipantDeserializer.java, rts/lra-examples/api-participant/src/main/java/io/narayana/rts/lra/ProxyBasedResource.java, rts/lra-examples/cdi-participant-with-coordinator/pom.xml, rts/lra-examples/cdi-participant/pom.xml, rts/lra-examples/lra-coordinator/pom.xml, rts/lra-examples/mixed-participant-with-coordinator/pom.xml, rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/FlightParticipant.java, rts/lra/hotel-service/src/main/java/io/narayana/rts/lra/demo/hotel/HotelParticipant.java, rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripController.java
https://issues.jboss.org/browse/JBTM-3103
The issue disables the api participant quckstarts (see issue for the reason).
This fix also partially address issue https://issues.jboss.org/browse/JBTM-3087 (and is needed to avoid compilation errors)
=> JBTM-3103 Disable LRA api quickstarts

spring/narayana-spring-boot/src/main/java/org/springframework/boot/jta/narayana/DbcpXADataSourceWrapper.java
The missing end " mixed up code source readability
when displaying on Github source view.
=> fix(javadoc comment): fix missing end " (double-quote)

rts/pom.xml
Signed-off-by: Michael Musgrove <mmusgrov@redhat.com>
https://issues.jboss.org/browse/JBTM-3116
This PR disables the LRA quickstarts until the narayana LRA spec implementation catches up with the latest round of spec API changes.
=> JBTM-3116 Temporarily disable LRA quickstarts

ArjunaJTA/jee_transactional_app/src/test/java/TestManagedBeanCustomerManager.java, ArjunaJTA/jee_transactional_app/src/test/java/org/jboss/narayana/quickstarts/TestManagedBeanCustomerManager.java
https://issues.jboss.org/browse/JBTM-3176
=> [JBTM-3176] stop using unnamed package as io.smallrye.metrics fails

rts/lra-examples/README.md, rts/lra-examples/cdi-participant/pom.xml, rts/lra/flight-service/pom.xml, rts/lra/hotel-service/pom.xml, rts/lra/trip-client/pom.xml, rts/lra/trip-controller/pom.xml, rts/pom.xml
https://issues.jboss.org/browse/JBTM-3177 (rename the id of the lra-filters artefact)
https://issues.jboss.org/browse/JBTM-3116 (re-enable LRA quickstarts)
=> JBTM-3177 Rename lra-filters module to narayana-lra

XTS/pom.xml
https://issues.jboss.org/browse/JBTM-3203
temporary workaround until wfly bom with jakarta dependency is released
https://github.com/wildfly/boms/blob/849ebf584bbf15c65d0bc42da239a290475f9228/jakartaee8/pom.xml#L120
=> [JBTM-3203] workaround: disabling XTS over SSL until WFLY bom with jakarta dependency is released

ArjunaJTA/jee_transactional_app/src/test/java/org/jboss/narayana/quickstarts/TestManagedBeanCustomerManager.java
I saw a CI failure where it seems that the number of customers was not as expected and it looked like a constraint violation on the PK. This PR should ensure if System.currentTimeMillis was the same at the two points then we would delay the run briefly to make sure the name would be different
=> TEST ONLY: If the test is faster than millis can be retrieved then wait for a second for the new name of the the customer to use

XTS/wsat-jta-multi_service/pom.xml
without the need to define any env property
https://issues.redhat.com/browse/JBTM-3267
=> [JBTM-3267] quickstart compilation with -DskipTests runs

.gitignore, ArjunaJTS/interop/glassfish/init.sh, ArjunaJTS/interop/glassfish/run.sh, ArjunaJTS/interop/glassfish/step1.sh, ArjunaJTS/interop/glassfish/step2.sh, ArjunaJTS/interop/glassfish/step3.sh, ArjunaJTS/interop/glassfish/step4.sh, README.md
https://issues.redhat.com/browse/JBTM-3263
When verifying JBTM-3132 we found the glassfish interop does not work on local machine. There is an `if` which makes this working on Narayana CI where glassfish sources are directly available. 
This PR changes the quickstart to work with glassfish 4.2.1 from github on local machine.
This needed few more changes as e.g. this version of glassfish was not starting when port `8080` was occupied by WFLY. Thus I changed order of the launching of the servers - glassfish is started first, changes the port to stop occupying the `8080` and then wildfly may be started.
=> [JBTM-3263] glassfish for interop quickstart is available on github

XTS/ssl/xts-over-ssh.sh, rts/lra-examples/run.sh, rts/lra/lra-test/pom.xml, rts/lra/pom.xml, rts/lra/run.sh, wildfly/commit-markable-resource/pom.xml
https://issues.redhat.com/browse/JBTM-3269
additional fix which is needed for the introduction of the new CI: https://issues.redhat.com/browse/JBTM-3274
=> [JBTM-3269] making commit markable resource working on JDK9+

wildfly/commit-markable-resource/pom.xml
https://issues.redhat.com/browse/JBTM-3269
fix JDK9+ execution for CMR quickstart on Windows
=> [JBTM-3269] commit markable quickstart to work on JKD9+ on Windows as well

transactionaldriver/transactionaldriver-standalone/pom.xml
https://issues.redhat.com/browse/JBTM-3305
=> JBTM-3305: quickstart transactionaldriver does not work on JDK11

jca-and-tomcat/pom.xml
https://issues.redhat.com/browse/JBTM-3306
=> JBTM-3306: Quickstart jca-and-tomcat doesn't work on JDK11

scripts/hudson/quickstart.sh
With the release of WFLY 22 it seems there was some change in artifacts provided by CI nightly builds. There could be more `SNAPSHOT.zip` files which the script handles wrongly now.
=> [SCRIPTS ONLY] on WFLY distribution download consider 'latest-SNAPSHOST' artifact

scripts/hudson/quickstart.bat, scripts/hudson/quickstart.sh
There happens to be (again) changes in the WildFly nightly build distribution zip archive. The prior structure of the `artifacts.zip` was flat where the zip contained directly the WildFly zip distribution (nightly build one). Now there is one more wrapper added and the `artifacts.zip` contains just a zip container which needs to be first unzipped before getting the distribution zip.
The shell changes should be able to work right with both - with the wrapped zip and with not wrapped zip.
=> [SCRIPTS ONLY] fix for WildFly changes of the structure of the nightly build zip wrapper

rts/lra/flight-service/pom.xml, rts/lra/hotel-service/pom.xml, rts/lra/trip-client/pom.xml, rts/lra/trip-controller/pom.xml
https://issues.redhat.com/browse/JBTM-3497
=> [JBTM-3497] Upgrade resteasy-client to 4.5.7.Final

rts/at/jta-service/README.md, rts/at/pom.xml
https://issues.redhat.com/browse/JBTM-3558
This PR temporarily disables the jta-service quickstart with a note that it should be tested against pre WildFly 25 releases (and to run on later WildFly versions JBTM-3558 needs fixing). I have done this because it blocks releasing narayana master and the defect is a test only issue with a workaround.
=> JBTM-3558 temporarily disable jta-service quickstart

jta-and-hibernate-standalone/src/main/java/org/jboss/narayana/quickstart/jta/QuickstartEntity.java, jta-and-hibernate-standalone/src/test/java/org/jboss/narayana/quickstart/jta/TestCase.java, transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/util/DBUtils.java
This seemed to help but still some of the quickstarts failed. It seems value was not allowed as a column name. Having a look after it seems to be in this list: http://h2database.com/html/advanced.html#keywords
=> Upgrading to H2 seems to have stopped allowing value as a column name

ArjunaJTA/pom.xml, ArjunaJTS/interop/pom.xml, XTS/pom.xml, compensating-transactions/pom.xml, pom.xml, rts/at/jta-service/pom.xml
https://issues.redhat.com/browse/JBTM-3584
=> JBTM-3584: Prevent quickstarts that require JDK11 from running on JDK8

rts/lra-examples/lra-jwt/wildfly/client/pom.xml
Hi! I found the pom file of project **_org.jboss.narayana.quickstart.rts.lra:lra-client:5.12.7.Final-SNAPSHOT_** introduced **_44_** dependencies. However, among them, **_13_** libraries (**_29%_**) are not used by your project. I list the redundant dependencies below (labelled as red ones in the figure):
javax.json:javax.json-api:jar:1.1.4:compile
com.sun.activation:jakarta.activation:jar:1.2.1:compile
org.reactivestreams:reactive-streams:jar:1.0.2:compile
jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile
com.github.java-json-tools:btf:jar:1.3:compile
com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:1.0.0.Final:compile …
=> Could org.jboss.narayana.quickstart.rts.lra:lra-client:5.12.7.Final-SNAPSHOT drop off redundant dependencies?

dbcp2-and-tomcat/pom.xml, pom.xml, rts/at/recovery/recovery1/pom.xml, rts/at/recovery/recovery2/pom.xml, rts/at/service/service1/pom.xml, rts/at/service/service1b/pom.xml, rts/at/simple/pom.xml, rts/at/undertow/pom.xml, rts/at/undertow/src/main/java/org/jboss/narayana/rts/TransactionAwareResource.java, rts/at/undertow/src/main/java/org/jboss/narayana/rts/TxnHelper.java, rts/lra-examples/lra-jwt/wildfly/client/pom.xml, transactionaldriver/transactionaldriver-and-tomcat/pom.xml, transactionaldriver/transactionaldriver-jpa-and-tomcat/pom.xml
https://issues.redhat.com/browse/JBTM-3668
Update resteasy-jaxrs and resteasy-client to newer version (resteasy-core-spi, resteasy-client-api, resteasy-core and resteasy-client)
=> [JBTM-3668] Update resteasy dependencies in quickstarts

ArjunaJTA/object_store/README.md, ArjunaJTA/object_store/pom.xml, ArjunaJTA/object_store/run.bat, ArjunaJTA/object_store/run.sh, ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/DummyXAResource.java, ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/JDBCStoreExample.java, ArjunaJTA/object_store/src/main/resources/h2-jbossts-properties.xml
https://issues.redhat.com/browse/JBTM-3724
Add a JDBCStore quickstart.
I want to add this one so that I can refer to it when indicating how LRA can be configured to use a database for its transaction logs.
I have added this directly to my JBTM-3699 tree (see pr #414) to facilitate the merge.
So only the final commit (8f3eaac) is relevant. If I can get PR 414 merged then I can create a PR with just one commit.
=> Jbtm 3699 and jbtm 3724

XTS/ssl/README.md, XTS/ssl/xts-over-ssh.sh, scripts/hudson/quickstart.sh
Modified scripts to:
* Uncouple server and client in `xts-ssl` (using the env var `JBOSS_ZIP`, which can also be defined from the CLI)
* Introduce the possibility to define `AS_BRANCH` from the CLI
=> Jbtm 3699 script improvement

compensating-transactions/mongodb-simple/README.md, compensating-transactions/mongodb-simple/pom.xml, compensating-transactions/mongodb-simple/src/test/java/org/jboss/narayana/quickstarts/mongodb/simple/BankingServiceTest.java, compensating-transactions/mongodb-simple/src/test/java/org/jboss/narayana/quickstarts/mongodb/simple/resources/BankingServiceJaxRs.java, compensating-transactions/mongodb-simple/src/test/java/org/jboss/narayana/quickstarts/mongodb/simple/resources/JaxRsActivator.java
This PR is a fix for an issue introduced with #424. Although #424 passed all tests, the annotation `@Container` doesn't work very well with `Arquillian`. In fact, the `@Container` annotation was able (somehow) to hide failures happening during the testing phase of this quickstart. To address this "false success", I have changed the way tests are executed: `Arquillian` and `testcontainers` are now executed locally. Please, refer to the code for more details.
=> Jbtm 3742 fixing false pass

pom.xml, rts/lra-examples/cdi-embedded/pom.xml, rts/lra-examples/cdi-participant/pom.xml
This PR resolves the following two problems (which came up during the migration to Jakarta) in the quickstart `lra-examples`:
* restore profile and fix NoClassDefFoundError: javax/annotation/Priority
* restore profile and fix Error: Could not find or load main class io.quarkus.bootstrap.runner.QuarkusEntryPoint
=> Lra-examples migrated to jakarta

rts/at/jta-service/jpa/pom.xml, rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/jaxrs/TaskResource.java, rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/Task.java, rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/TaskDao.java, rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/TaskDaoImpl.java, rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/UserTable.java, rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/UserTableDao.java, rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/UserTableDaoImpl.java, rts/at/jta-service/jpa/src/test/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/test/TaskResourceTest.java, rts/at/jta-service/jpa/src/test/resources/arquillian.xml
This PR fixes the quickstart in `rts/at/jta-service/jpa`, which was disabled during the migration to Jakarta because of the exception `ModuleNotFoundException: org.codehaus.jettison`. NB: this PR renames `User` to `UserTable` to eliminate the name conflict that affects H2 (`User` is a reserved table name)
=> [JBTM-3699] rts/at/jta-service/jpa fixed

rts/lra-examples/run.sh
Our CI doesn't like relative paths. This PR is the workaround. I already [tested](https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/narayana_6.0-quickstarts/7/) this PR (the quickstart with MongoDB fails because there isn't any docker/podman environment in our CI)
=> [JBTM-3699] change of path in run.sh for the quickstart lra-examples

compensating-transactions/pom.xml
Until our CI will not be able to manage quickstarts using docker we want those quickstarts to be disabled. In fact those quickstarts might work locally but not yet on our CI infrastructure. 
Additionally we don't want those quickstarts' errors to influence contributors' PRs test result.
=> Disable mongodb quickstart

ArjunaJTA/object_store/pom.xml, pom.xml, rts/at/annotation/flight-service/pom.xml, rts/at/annotation/hotel-service/pom.xml, rts/at/annotation/pom.xml, rts/at/annotation/trip-service/pom.xml
Update quarkus to 3.4.2 version
This PR will be on hold until https://github.com/jbosstm/narayana/pull/2177 get merged.
Note: I added an extra commit in order to fix the failure shown in [CI build](https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/btny-pulls-narayana-quickstart/17/)
=> quarkus update to 3.4.2

ArjunaCore/txoj/pom.xml, ArjunaJTA/jakarta_transaction/pom.xml, ArjunaJTA/object_store/pom.xml
Dependency jboss-logging is needed in order to fix errors shown in build: https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/narayana-quickstarts/jdk=openJDK17,label=jnlp-agent/143/console
=> dependency jboss-logging needed in some quickstarts

XTS/pom.xml, XTS/ssl/README.md
https://issues.redhat.com/browse/JBTM-3850
Parent issue is https://issues.redhat.com/browse/JBTM-3849 
related to https://issues.redhat.com/browse/WFLY-18515
This quickstart will be disabled until https://issues.redhat.com/browse/JBTM-3851
Since the wsat-simple has been removed from wildfly/quickstart the ssl quickstart doesn't work anymore, so disabling it.
=> [JBTM-3850] Disable not working XTS/ssl quickstart

compensating-transactions/travel-agent/pom.xml
partially solve: https://issues.redhat.com/browse/JBTM-3864 
I disabled not working arq test from compensation quickstart, I am OK with removing it if not necessary anymore.
Related to https://github.com/jbosstm/narayana/pull/2233
=> [JBTM-3864] Compensation is removed from WildFly

XTS/raw-xts-api-demo/core/pom.xml, compensating-transactions/travel-agent/pom.xml, jta-and-hibernate-standalone/pom.xml, pom.xml, transactionaldriver/transactionaldriver-standalone/pom.xml, wildfly/commit-markable-resource/pom.xml
This PR includes commit from JBTM-3870, which upgrades byteman dependency.
note: ws-t11 dependency needs the 'api' classifier.
=> Build 6.0 against JDK 21 

ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/FileStoreExample.java, ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/HornetqStoreExample.java, ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/JDBCStoreExample.java, ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/Util.java, ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/VolatileStoreExample.java
https://issues.redhat.com/browse/JBTM-3965
The object_store quickstart needs to add records to the store for all store types (as it's coded only the JDBC store does so).
=> JBTM-3965 Allways enlist participants

pom.xml
Update Quarkus to 3.8 which is a LTS.
A follow up PR will update Quarkus to 3.15 LTS or higher, see https://github.com/jbosstm/quickstart/pull/470
=> Quarkus to 3.8.6

pom.xml, rts/at/annotation/pom.xml, rts/lra-examples/cdi-embedded/pom.xml, rts/lra-examples/cdi-participant/pom.xml, rts/lra-examples/coordinator-quarkus/pom.xml
Update quarkus to 3.17.5
Since Quarkus 3.9.x Quarkus rest default is resteasy reactive  (see https://quarkus.io/guides/rest-migration).
Since  Narayana LRA is a servlet-based JAX-RS it is not possible to move now to  Quarkus resteasy reactive, which is the default choice, is not feasible at the moment (see https://quarkus.io/guides/rest-migration#servlets). So we need to stick with reasteasy classic for the moment.
cc @mmusgrov @tomjenkinson
=> Quarkus update to 3.17.x
