blacktie/integration1/xatmi_adapter/src/main/resources/META-INF/hornetq-jms.xml
blacktie/jatmibroker-xatmi/mdb-xatmi-service/src/main/resources/META-INF/hornetq-jms.xml

https://issues.jboss.org/browse/JBTM-2451

JBTM-2451 Updated to move to activemq config

---

XTS/raw-xts-api-demo/test/pom.xml
XTS/wsat-jta-multi_hop/pom.xml
XTS/wsat-jta-multi_service/pom.xml
compensating-transactions/mongodb-simple/pom.xml
compensating-transactions/non-transactional_resource/pom.xml
compensating-transactions/travel-agent/pom.xml
jta-1_2-in-wildfly/pom.xml
rts/at/demo/pom.xml
rts/at/jta-service/pom.xml
rts/at/recovery/recovery1/pom.xml
rts/at/recovery/recovery2/pom.xml
rts/at/service/service1/pom.xml
rts/at/service/service2/pom.xml

https://issues.jboss.org/browse/JBTM-2501

[JBTM-2501] Remove quickstart dependency on WildFly version

---

XTS/raw-xts-api-demo/test/pom.xml

https://issues.jboss.org/browse/JBTM-2502

[JBTM-2502] Set java.awt.headless property to false for the raw xts quickstart

---

blacktie/integration1/ejb/ear/pom.xml
blacktie/integration1/xatmi_adapter/ear/pom.xml
blacktie/jatmibroker-xatmi/mdb-xatmi-service/ear/pom.xml

https://issues.jboss.org/browse/JBTM-2506

JBTM-2506 Upgrade the wildfly-maven-plugin to 1.0.2.Final

---

jts-docker/README.md

Waiting for https://github.com/jboss-dockerfiles/narayana/pull/5

Docker QS README update

---

blacktie/integration1/README
blacktie/jatmibroker-xatmi/mdb-xatmi-service/README
blacktie/nbf/README
blacktie/test/blacktie-linux.sh
blacktie/test/blacktie-vc9x32.bat
blacktie/test/initializeBlackTie.xml
blacktie/xatmi/fooapp/README
blacktie/xatmi/library/README
blacktie/xatmi/mappedNames/README
blacktie/xatmi/queues/README
blacktie/xatmi/replyTo/README
blacktie/xatmi/security/README
blacktie/xatmi/svrInitDoneFunctions/README
blacktie/xatmi/topics/README
blacktie/xatmi/txfooapp/README

https://issues.jboss.org/browse/JBTM-2498

JBTM-2498 Incomplete BlackTie quickstart documentation

---

XTS/wsat-jta-multi_hop/README.md
XTS/wsat-jta-multi_hop/pom.xml
XTS/wsat-jta-multi_hop/src/test/resources/arquillian.xml
XTS/wsat-jta-multi_service/README.md
XTS/wsat-jta-multi_service/pom.xml
XTS/wsat-jta-multi_service/src/test/resources/arquillian.xml
compensating-transactions/mongodb-simple/pom.xml
compensating-transactions/non-transactional_resource/pom.xml
compensating-transactions/travel-agent/pom.xml
compensating-transactions/travel-agent/src/test/resources/arquillian.xml
jta-1_2-in-wildfly/README.md
jta-1_2-in-wildfly/pom.xml
jta-1_2-in-wildfly/src/test/resources/arquillian.xml
rts/at/jta-service/README.md
rts/at/jta-service/jms/pom.xml
rts/at/jta-service/jms/src/test/resources/arquillian.xml
rts/at/jta-service/jpa/src/test/resources/arquillian.xml
rts/at/jta-service/pom.xml

https://issues.jboss.org/browse/JBTM-2564

JBTM-2564 IPv6 args for quickstarts

---

wildfly/setCheckedActionFactoryExample/README.md

https://issues.jboss.org/browse/JBTM-2591

JBTM-2591 Improve instructions for WildFly quickstart

---

ArjunaJTA/jee_transactional_app/pom.xml
ArjunaJTA/pom.xml
ArjunaJTS/pom.xml
XTS/raw-xts-api-demo/test/pom.xml
XTS/wsat-jta-multi_hop/pom.xml
XTS/wsat-jta-multi_service/pom.xml
compensating-transactions/mongodb-simple/pom.xml
compensating-transactions/non-transactional_resource/pom.xml
compensating-transactions/travel-agent/pom.xml
jca-and-tomcat/pom.xml
jta-1_2-in-wildfly/pom.xml
jta-and-hibernate/pom.xml
jts-docker/pom.xml
rts/at/jta-service/jms/pom.xml
rts/at/jta-service/pom.xml

https://issues.jboss.org/browse/JBTM-2611

JBTM-2611 Updated to 2.19.1 version of surefire

---

pom.xml
spring/README.md
spring/jta/pom.xml
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/Launch.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/config/DatabaseConfig.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/config/DummyXAConfig.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/config/H2DataSource.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/config/RecoveryManagerConfig.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/config/TransactionConfig.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/service/ExampleService.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/xa/DummyXAResource.java
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/xa/DummyXAResourceRecovery.java
spring/jta/src/main/resources/jbossts-properties.xml
spring/jta/src/main/resources/log4j.properties
spring/jta/src/test/java/org/jboss/narayana/quickstart/spring/TestJTA.java
spring/jta/src/test/resources/log4j.properties
spring/pom.xml

https://issues.jboss.org/browse/JBTM-855

JBTM-855 Update to add the jta spring example

---

jts-atomic-app/.gitignore
jts-atomic-app/Dockerfile
jts-atomic-app/Nulecule
jts-atomic-app/README.md
jts-atomic-app/Vagrantfile
jts-atomic-app/artifacts/docker/jacorb-name-server_run
jts-atomic-app/artifacts/docker/jts-transaction-service_run

https://issues.jboss.org/browse/JBTM-2298

[JBTM-2298] JTS and Jacorb atomic app

---

karaf/osgi-jta/README.md
karaf/osgi-jta/pom.xml
karaf/osgi-jta/src/main/java/org/jboss/narayana/quickstart/osgi/CommitExample.java
karaf/osgi-jta/src/main/java/org/jboss/narayana/quickstart/osgi/RecoveryExample.java
karaf/osgi-jta/src/main/java/org/jboss/narayana/quickstart/xa/DummyXAResource.java
karaf/osgi-jta/src/main/java/org/jboss/narayana/quickstart/xa/DummyXAResourceRecovery.java
pom.xml

https://issues.jboss.org/browse/JBTM-2619

JBTM-2619 Create a quickstart to show using of the narayana-osgi-jta bundle (karaf)

---

wiki-example/README
wiki-example/build.xml
wiki-example/resources/jacorb.properties
wiki-example/resources/jbossts-properties.xml
wiki-example/resources/log4j.dtd
wiki-example/resources/log4j.xml
wiki-example/src/com/arjuna/ats/tools/TxTest.java
wiki-example/src/org/jboss/jbossts/qa/astests/META-INF/ejb-jar.xml
wiki-example/src/org/jboss/jbossts/qa/astests/META-INF/jboss.xml
wiki-example/src/org/jboss/jbossts/qa/astests/ejb2/EJB2Home.java
wiki-example/src/org/jboss/jbossts/qa/astests/ejb2/EJB2Remote.java
wiki-example/src/org/jboss/jbossts/qa/astests/ejb2/EJB2StatelessBean.java
wiki-example/src/org/jboss/jbossts/qa/astests/ejb3/EJB3Remote.java
wiki-example/src/org/jboss/jbossts/qa/astests/ejb3/EJB3StatelessBean.java
wiki-example/src/org/jboss/jbossts/qa/astests/ejbutil/TestResource.java
wiki-example/src/org/jboss/jbossts/qa/astests/ejbutil/Util2.java
wiki-example/src/org/jboss/jbossts/qa/astests/ejbutil/Util2.java.orig
wiki-example/src/org/jboss/jbossts/qa/astests/resources/java.policy

Update this once its merged: https://developer.jboss.org/wiki/TransactionPropagationWithJBoss

JTS wiki example

---

karaf/osgi-jta/README.md
karaf/osgi-jta/src/main/java/org/jboss/narayana/quickstart/osgi/HeuristicExample.java
karaf/osgi-jta/src/main/java/org/jboss/narayana/quickstart/xa/DummyXAResource.java

https://issues.jboss.org/browse/JBTM-2686

JBTM-2686 Update to add a Heuristic example in the karaf osgi-jta quickstart

---

ArjunaJTS/pom.xml
rts/at/demo/pom.xml
rts/at/recovery/recovery1/pom.xml
rts/at/recovery/recovery2/pom.xml
rts/at/service/service1/README.md
rts/at/service/service1/pom.xml
rts/at/service/service1b/README.md
rts/at/service/service1b/pom.xml
rts/at/service/service1b/run.sh
rts/at/service/service2b/pom.xml
rts/at/simple/README.md
rts/at/simple/pom.xml
rts/at/undertow/pom.xml

https://issues.jboss.org/browse/JBTM-2699

JBTM-2699 Add missing dependency

---

XTS/wsat-jta-multi_hop/README.md
XTS/wsat-jta-multi_hop/pom.xml
XTS/wsat-jta-multi_service/README.md
XTS/wsat-jta-multi_service/pom.xml

https://issues.jboss.org/browse/JBTM-2671

[JBTM-2671] Correct TXBridge quickstart execution steps

---

STM/jta/pom.xml
jca-and-hibernate/pom.xml
jca-and-tomcat/pom.xml
jta-1_2-standalone/pom.xml
jta-and-hibernate-standalone/pom.xml
karaf/osgi-jta/pom.xml
spring/jta/pom.xml

https://issues.jboss.org/browse/JBTM-2749

JBTM-2749 Updated to 7.3.4.Final

---

karaf/osgi-jta/pom.xml

https://issues.jboss.org/browse/JBTM-2761

JBTM-2761 Added nexus for the OSGi quickstart

---

rts/at/jta-service/jms/src/test/java/org/jboss/jbossts/resttxbridge/quickstart/jms/QueueResourceTest.java
rts/at/jta-service/jpa/src/test/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/test/TaskResourceTest.java

https://issues.jboss.org/browse/JBTM-2789

JBTM-2789 Replace usage of deprecated RESTEasy APIs

---

build.bat
scripts/hudson/quickstart.bat

https://issues.jboss.org/browse/JBTM-2795

JBTM-2795 Quickstart can not build the karaf

---

blacktie/pom.xml
build.bat
pom.xml
scripts/hudson/quickstart.bat
scripts/hudson/quickstart.sh

https://issues.jboss.org/browse/JBTM-2820

JBTM-2820 diable the karaf build and the osgi quickstart

---

blacktie/pom.xml
build.bat
tools/download-maven.ps1
tools/download-maven.sh

https://issues.jboss.org/browse/JBTM-2816

JBTM-2816 Renamed mvn to mvn.cmd

---

XTS/raw-xts-api-demo/test/pom.xml

https://issues.jboss.org/browse/JBTM-2838

[JBTM-2838] Add ipv6 profile to XTS war api quickstart

---

XTS/pom.xml
XTS/ssl/.gitignore
XTS/ssl/README.md
XTS/ssl/pom.xml
XTS/ssl/xts-over-ssh.sh

Adding script automatizing XTS test over SSL. Till now there was only a text explanation how to proceed with configuration but the functionality was not checked in CI.
https://issues.jboss.org/browse/JBTM-2882

[JBTM-2882] automatize quickstart of xts over ssl with sh script

---

spring/narayana-spring-boot/pom.xml

https://issues.jboss.org/browse/JBTM-2895

JBTM-2895 Upgrade the spring-boot to 1.5.3.RELEASE

---

STM/vertx/README.adoc
STM/vertx/demo.sh
STM/vertx/pom.xml
STM/vertx/src/main/java/demo/demo12/PersistentSharedTheatreVerticle.java
STM/vertx/src/main/java/demo/demo12/TheatreVerticle.java
STM/vertx/src/main/java/demo/demo12/TheatreVerticleImpl.java
STM/vertx/src/main/java/demo/demo12/VolatileTheatreVerticle.java
STM/vertx/src/main/java/demo/demo3/TripSTMVerticle.java
STM/vertx/src/main/java/demo/demo3/TripVerticleImpl.java
STM/vertx/src/main/java/demo/domain/Booking.java
STM/vertx/src/main/java/demo/domain/ServiceResult.java
STM/vertx/src/main/java/demo/domain/TaxiService.java
STM/vertx/src/main/java/demo/domain/TaxiServiceImpl.java
STM/vertx/src/main/java/demo/domain/TheatreService.java
STM/vertx/src/main/java/demo/domain/TheatreServiceImpl.java
STM/vertx/src/main/java/demo/util/ProgArgs.java
STM/vertx/src/main/java/demo/util/Stress.java
STM/vertx/src/main/java/demo/util/StressTest.java
STM/vertx/src/main/resources/jbossts-properties.xml

https://issues.jboss.org/browse/JBTM-2889

JBTM-2889 Using STM with vert.x

---

ArjunaJTS/interop/glassfish/pom.xml
pom.xml
scripts/hudson/quickstart.bat
transactionaldriver-and-tomcat/.gitignore
transactionaldriver-and-tomcat/README.md
transactionaldriver-and-tomcat/pom.xml
transactionaldriver-and-tomcat/run.sh
transactionaldriver-and-tomcat/src/main/java/io/narayana/StringDao.java
transactionaldriver-and-tomcat/src/main/java/io/narayana/StringsApplication.java
transactionaldriver-and-tomcat/src/main/java/io/narayana/StringsResource.java
transactionaldriver-and-tomcat/src/main/resources/h2recoveryproperties.xml
transactionaldriver-and-tomcat/src/main/webapp/META-INF/context.xml
transactionaldriver-and-tomcat/src/main/webapp/WEB-INF/web.xml

https://issues.jboss.org/browse/JBTM-2766

JBTM-2766 Show a quickstart working for transactionaldriver in Tomcat

---

jta-and-hibernate-standalone/pom.xml

https://issues.jboss.org/browse/JBTM-2900

JBTM-2900 byteman is loaded properly while using ibm jdk

---

STM/jta/pom.xml
jta-1_2-standalone/pom.xml
jta-and-hibernate-standalone/pom.xml
transactionaldriver-and-tomcat/run.sh
transactionaldriver-jpa-and-tomcat/run.sh

https://issues.jboss.org/browse/JBTM-2913
Won't work as needs the Narayana change: https://github.com/jbosstm/narayana/pull/1198
Also includes an upgrade to Tomcat

JBTM-2913 Do not independently request the SPI

---

rts/lra/flight-service/pom.xml
rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/participant/FlightController.java
rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/service/FlightService.java
rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/model/Booking.java
rts/lra/hotel-service/pom.xml
rts/lra/hotel-service/src/main/java/io/narayana/rts/lra/demo/hotel/participant/HotelController.java
rts/lra/hotel-service/src/main/java/io/narayana/rts/lra/demo/hotel/service/HotelService.java
rts/lra/hotel-service/src/main/java/io/narayana/rts/lra/demo/model/Booking.java
rts/lra/lra-test/pom.xml
rts/lra/minishift.sh
rts/lra/pom.xml
rts/lra/run.sh
rts/lra/trip-client/pom.xml
rts/lra/trip-client/src/main/java/TripClient.java
rts/lra/trip-client/src/main/java/model/Booking.java
rts/lra/trip-controller/pom.xml
rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/model/Booking.java
rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/participant/TripController.java
rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/service/TripService.java

NO_WIN
Requires https://github.com/jbosstm/narayana/pull/1215

JBTM-1488 Updated with better rest coordinates

---

.gitignore
rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/FlightParticipant.java
rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/FlightService.java
rts/lra/hotel-service/src/main/java/io/narayana/rts/lra/demo/hotel/HotelParticipant.java
rts/lra/minishift.sh
rts/lra/trip-client/src/main/java/TripClient.java
rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripController.java
rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripService.java

On verifying fix: 
* https://issues.jboss.org/browse/JBTM-2951
I needed to run the lra quickstart and having troubles with few things thus adding this update.

Lra quickstart fixes

---

scripts/hudson/quickstart.sh

changing the sh script to be able to change the branch where narayana is build from and define what is narayana version to be used in quickstarts run

[SCRIPTS ONLY] making possible to parametrize what the narayana repo and branch

---

STM/pessimistic/src/main/java/PCCExample.java

https://issues.jboss.org/browse/JBTM-2960

JBTM-2960 minor update to STM quickstart

---

ArjunaJTS/recovery/pom.xml

https://issues.jboss.org/browse/JBTM-2966

JBTM-2966 add dependency on jboss-transaction-spi

---

ArjunaJTS/interop/glassfish/step1.sh
atsintegration/examples/classes/com/arjuna/jta/distributed/example/server/impl/ServerImpl.java
jca-and-tomcat/src/main/resources/transaction.xml
spring/jta/src/main/resources/jbossts-properties.xml
transactionaldriver/transactionaldriver-standalone/src/main/resources/jbossts-properties.xml

Adding JTAActionStatusServiceXAResourceOrphanFilter to configured orphan filters

JBTM-2583 Adding JTAActionStatusServiceXAResourceOrphanFilter

---

dbcp2-and-tomcat/.gitignore
dbcp2-and-tomcat/pom.xml
dbcp2-and-tomcat/run.sh
jca-and-tomcat/pom.xml
transactionaldriver/transactionaldriver-and-tomcat/pom.xml
transactionaldriver/transactionaldriver-and-tomcat/run.sh
transactionaldriver/transactionaldriver-jpa-and-tomcat/pom.xml
transactionaldriver/transactionaldriver-jpa-and-tomcat/run.sh

https://issues.jboss.org/browse/JBTM-3008

JBTM-3008 Upgrade to Tomcat 9

---

scripts/hudson/quickstart.bat
scripts/hudson/quickstart.sh

JBTM-3018 Build microprofile-lra dependency

---

rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/TaskDaoImpl.java
rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/UserDaoImpl.java

https://issues.jboss.org/browse/JBTM-3043
Fixes the build failure due to hibernate removing support for legacy style HQL queries

JBTM-3043 Use JPQL style queries

---

dbcp2-and-tomcat/pom.xml
transactionaldriver/transactionaldriver-and-tomcat/pom.xml
transactionaldriver/transactionaldriver-jpa-and-tomcat/pom.xml

Requires: https://github.com/jbosstm/narayana/pull/1348

JBTM-3030 Moved Tomcat to https://github.com/web-servers/narayana-tomcat

---

transactionaldriver/transactionaldriver-standalone/README.md
transactionaldriver/transactionaldriver-standalone/pom.xml
transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/DriverDirectRecoverable.java
transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/DriverIndirectRecoverable.java
transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/DriverProvidedXADataSource.java
transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/recovery/Ds1XAResourceRecovery.java
transactionaldriver/transactionaldriver-standalone/src/main/java/io/narayana/util/DBUtils.java
transactionaldriver/transactionaldriver-standalone/src/test/java/io/narayana/TransactionalDriverTest.java

https://issues.jboss.org/browse/JBTM-3070
plus added a better way how to switch from H2 to PostgreSQL

[JBTM-3070] fix for transactional driver quickstart to not using reflection

---

README.md
agroal/README.md
agroal/pom.xml
agroal/src/main/java/io/narayana/AgroalDatasource.java
agroal/src/main/java/io/narayana/util/AgroalH2Utils.java
agroal/src/main/resources/jbossts-properties.xml
agroal/src/main/resources/logging.properties
agroal/src/main/resources/xaexception.rmfail.btm
agroal/src/test/java/io/narayana/AgroalTest.java
jca-and-hibernate/pom.xml
jca-and-hibernate/src/test/resources/h2-xa-ds.xml
jca-and-tomcat/pom.xml
spring/jta/pom.xml
spring/jta/src/main/java/org/jboss/narayana/quickstart/spring/config/DatabaseConfig.java
transactionaldriver/transactionaldriver-standalone/pom.xml
wildfly/commit-markable-resource/pom.xml

See https://agroal.github.io/about.html

Adding quickstart showing integration with Agroal

---

ArjunaJTA/jee_transactional_app/pom.xml
XTS/wsat-jta-multi_hop/pom.xml
XTS/wsat-jta-multi_service/pom.xml
compensating-transactions/mongodb-simple/pom.xml
compensating-transactions/non-transactional_resource/pom.xml
compensating-transactions/travel-agent/pom.xml
jta-1_2-in-wildfly/pom.xml
rts/at/jta-service/pom.xml
wildfly/commit-markable-resource/pom.xml

https://issues.jboss.org/browse/JBTM-3076

JBTM-3076 upgrade the arquillian core and arquillian wildfly

---

XTS/wsat-jta-multi_hop/pom.xml
XTS/wsat-jta-multi_service/pom.xml
blacktie/integration1/ejb/ear/pom.xml
blacktie/integration1/ejb/pom.xml
blacktie/integration1/xatmi_adapter/ear/pom.xml
blacktie/integration1/xatmi_adapter/pom.xml
blacktie/jatmibroker-xatmi/mdb-xatmi-service/ear/pom.xml
blacktie/jatmibroker-xatmi/mdb-xatmi-service/pom.xml
rts/at/demo/pom.xml
rts/at/recovery/recovery1/pom.xml
rts/at/recovery/recovery2/pom.xml
rts/at/service/service1/pom.xml
rts/at/service/service2/pom.xml
rts/at/service/service2b/pom.xml

!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB BLACKTIE !XTS !PERF !RTS !AS_TESTS !TOMCAT !JACOCO !LRA !DB_TESTS !JDK11 !WIN

JBTM-3136 Use https for dependencies

---

XTS/ssl/xts-over-ssh.sh

https://issues.jboss.org/browse/JBTM-3152

[JBTM-3152] fix for XTS SSL quickstart failures

---

rts/lra/README.adoc
rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/FlightParticipant.java
rts/lra/flight-service/src/main/java/io/narayana/rts/lra/demo/flight/FlightService.java
rts/lra/hotel-service/src/main/java/io/narayana/rts/lra/demo/hotel/HotelParticipant.java
rts/lra/lra-coordinator/Dockerfile
rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripController.java
rts/lra/trip-controller/src/main/java/io/narayana/rts/lra/demo/tripcontroller/TripService.java

Signed-off-by: mkralik3 <mkralik@redhat.com>

Updated lra quickstart

---

rts/lra/trip-client/pom.xml

Updated jackson-databind to 2.9.9.1

---

rts/lra-examples/lra-coordinator/pom.xml

JBTM-3207 Use the thorntail classified jar

---

rts/lra/flight-service/pom.xml
rts/lra/hotel-service/pom.xml
rts/lra/trip-client/pom.xml
rts/lra/trip-controller/pom.xml

Upgrade to Jackson 2.9.10.1

---

XTS/ssl/xts-over-ssh.sh

https://issues.redhat.com/browse/JBTM-3264

[JBTM-3264] XTS ssl quickstart to not place temporary files to source directory

---

XTS/ssl/xts-over-ssh.sh

https://issues.redhat.com/browse/JBTM-3275
A fix for the stuck happened at 
http://narayanaci1.eng.hst.ams2.redhat.com/job/btny-pulls-narayana-quickstart/13/console

[JBTM-3275] when waiting on server timed-out, we need to stop the server

---

rts/lra-examples/lra-coordinator/pom.xml
rts/lra-examples/run.sh
rts/lra/flight-service/pom.xml
rts/lra/hotel-service/pom.xml
rts/lra/run.sh
rts/lra/trip-controller/pom.xml
transactionaldriver/transactionaldriver-and-tomcat/run.sh

https://issues.redhat.com/browse/JBTM-3277
https://issues.redhat.com/browse/JBTM-3282

[JBTM-3277] force curl to use ipv4 with LRA and tomcat

---

dbcp2-and-tomcat/pom.xml
dbcp2-and-tomcat/run.sh
dbcp2-and-tomcat/src/main/webapp/WEB-INF/web.xml
transactionaldriver/transactionaldriver-and-tomcat/pom.xml
transactionaldriver/transactionaldriver-and-tomcat/run.sh
transactionaldriver/transactionaldriver-jpa-and-tomcat/pom.xml
transactionaldriver/transactionaldriver-jpa-and-tomcat/run.sh

https://issues.redhat.com/browse/JBTM-3301

[JBTM-3301] updating Tomcat integration code to JWS version and make it running on JDK9+

---

ArjunaJTS/interop/glassfish/run.sh
ArjunaJTS/interop/glassfish/step3.sh
XTS/ssl/xts-over-ssh.sh
blacktie/integration1/run.sh
blacktie/jatmibroker-xatmi/mdb-xatmi-service/run.sh
blacktie/test/blacktie-linux.sh
dbcp2-and-tomcat/run.sh
rts/at/demo/run.sh
rts/lra-examples/run.sh
rts/lra/run.sh
scripts/hudson/quickstart.sh
spring/camel-with-narayana-spring-boot/run.sh
transactionaldriver/transactionaldriver-and-tomcat/run.sh

https://issues.redhat.com/browse/JBTM-3322

[JBTM-3322] run.sh shell scripts consider MFACTOR to adjust timeout/sleep time

---

ArjunaJTA/object_store/src/main/java/org/jboss/narayana/jta/quickstarts/HornetqStoreExample.java

https://issues.redhat.com/browse/JBTM-3333

[JBTM-3333] Update the ArjunaJTA/object_store quickstart.

---

ArjunaJTS/interop/glassfish/init.sh
ArjunaJTS/interop/glassfish/step3.sh
ArjunaJTS/interop/glassfish/step7.sh
scripts/hudson/quickstart.sh

https://issues.redhat.com/browse/JBTM-3369

[JBTM-3369] jboss-cli processing permitted only for running app server

---

rts/lra-examples/run.sh

https://issues.redhat.com/browse/JBTM-3378
https://issues.redhat.com/browse/JBTM-3375

[JBTM-3375][JBTM-3378] the REST endpoint of the LRA recovery coordinator was moved

---

rts/lra-examples/cdi-participant/pom.xml
rts/lra/README.adoc
rts/lra/flight-service/Dockerfile
rts/lra/flight-service/pom.xml
rts/lra/hotel-service/pom.xml
rts/lra/minishift.sh
rts/lra/trip-client/pom.xml
rts/lra/trip-controller/Dockerfile
rts/lra/trip-controller/pom.xml

this change was introduced by JBTM-3393
https://issues.redhat.com/browse/JBTM-3393

[JBTM-3393] changing the 'lra.http.host' for property `lra.coordinator.url`

---

rts/README.md
rts/lra-examples/lra-jwt/README.md
rts/lra-examples/lra-jwt/pom.xml
rts/lra-examples/lra-jwt/wildfly/README.md
rts/lra-examples/lra-jwt/wildfly/client/pom.xml
rts/lra-examples/lra-jwt/wildfly/client/src/main/java/org/jboss/jaxrsjwt/auth/JwtManager.java
rts/lra-examples/lra-jwt/wildfly/client/src/main/java/org/jboss/jaxrsjwt/client/JwtRestClient.java
rts/lra-examples/lra-jwt/wildfly/configure-elytron.cli
rts/lra-examples/lra-jwt/wildfly/lra-coordinator/pom.xml
rts/lra-examples/lra-jwt/wildfly/lra-coordinator/src/main/webapp/WEB-INF/web.xml
rts/lra-examples/lra-jwt/wildfly/pom.xml
rts/lra-examples/lra-jwt/wildfly/restore-configuration.cli
rts/lra-examples/pom.xml

https://issues.redhat.com/browse/JBTM-3309

JBTM-3309 : Quickstart : Securing Narayana LRA endpoints, using Json web token on Wildfly.

---

tools/download-maven.sh

https://issues.redhat.com/browse/JBTM-3432

JBTM-3432 Upgrade maven to 3.6.3 (the most recent)

---

rts/lra-examples/README.md
rts/lra-examples/cdi-embedded/README.md
rts/lra-examples/cdi-embedded/pom.xml
rts/lra-examples/cdi-embedded/src/main/java/io/narayana/rts/lra/CdiBasedResource.java
rts/lra-examples/cdi-embedded/src/main/java/io/narayana/rts/lra/StateHolder.java
rts/lra-examples/cdi-embedded/src/main/resources/META-INF/beans.xml
rts/lra-examples/cdi-embedded/src/main/resources/application.properties
rts/lra-examples/cdi-embedded/src/main/resources/jbossts-properties.xml
rts/lra-examples/cdi-participant/README.md
rts/lra-examples/lra-coordinator/README.md
rts/lra-examples/lra-coordinator/pom.xml
rts/lra-examples/pom.xml
rts/lra-examples/run.sh
tools/download-maven.sh

https://issues.redhat.com/browse/JBTM-3430
Adds a quickstart to show how use a quarkus based coordinator facilitated by PR jbosstm/narayana#1788

JBTM-3430 include an example of running the coordinator with quarkus

---

build.bat
tools/download-maven.ps1

This PR updates the Windows script to fetch the maven version 3.6.3 instead of the older 3.2.5

Modified the Windows script to update maven to 3.6.3

---

rts/lra-examples/README.md
rts/lra-examples/cdi-embedded/README.md
rts/lra-examples/cdi-embedded/pom.xml
rts/lra-examples/cdi-participant/README.md
rts/lra-examples/cdi-participant/pom.xml
rts/lra-examples/cdi-participant/src/main/resources/application.properties
rts/lra-examples/lra-coordinator/README.md
rts/lra-examples/lra-coordinator/pom.xml
rts/lra-examples/run.sh

https://issues.redhat.com/browse/JBTM-3512

JBTM-3512 replace thorntail with quarkus

---

ArjunaJTA/object_store/pom.xml

JBTM-3529 ArjunaJTA object store quickstart failure

JBTM-3529 Upgrade activemq artemis to 2.18.0

---

jca-and-hibernate/pom.xml
jca-and-tomcat/pom.xml
jta-and-hibernate-standalone/pom.xml
rts/lra/pom.xml
spring/jta/pom.xml

Miscellaneous dependency updates

dependency-updates

---

jca-and-hibernate/pom.xml
jca-and-tomcat/pom.xml
jta-and-hibernate-standalone/pom.xml

log4j-version-bump

---

spring/jta/pom.xml

version-bump

---

karaf/osgi-jta/README.md
pom.xml

https://issues.redhat.com/browse/JBTM-3564

JBTM-3565 disable karaf quickstart

---

rts/at/jta-service/jpa/pom.xml
rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/jaxrs/TaskResource.java
rts/at/jta-service/jpa/src/main/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/model/Task.java
rts/at/jta-service/jpa/src/test/java/org/jboss/narayana/quickstart/rest/bridge/inbound/jpa/test/TaskResourceTest.java
rts/at/pom.xml

https://issues.redhat.com/browse/JBTM-3558

JBTM-3558: Use json.api instead of jettison for the REST-AT jms/jpa quickstarts

---

rts/lra/.gitignore
rts/lra/README.adoc
rts/lra/flight-service/Dockerfile
rts/lra/flight-service/pom.xml
rts/lra/flight-service/src/main/resources/application.properties
rts/lra/hotel-service/Dockerfile
rts/lra/hotel-service/pom.xml
rts/lra/hotel-service/src/main/resources/application.properties
rts/lra/minishift.sh
rts/lra/pom.xml
rts/lra/run.sh
rts/lra/trip-client/pom.xml
rts/lra/trip-controller/Dockerfile
rts/lra/trip-controller/pom.xml
rts/lra/trip-controller/src/main/resources/application.properties
rts/pom.xml

https://issues.redhat.com/browse/JBTM-3557

JBTM-3557: Migrate LRA booking quickstart from throntail to quarkus

---

transactionaldriver/transactionaldriver-standalone/pom.xml

upgrade postgresql dependency

---

rts/lra/hotel-service/pom.xml
rts/lra/trip-client/pom.xml
rts/lra/trip-controller/pom.xml

CVE-2020-25633

---

XTS/ssl/xts-over-ssh.sh

https://issues.redhat.com/browse/JBTM-3593

JBTM-3593 Use Elytron for SSL

---

rts/lra-examples/cdi-embedded/pom.xml
rts/lra-examples/cdi-participant/pom.xml
rts/lra-examples/run.sh

(https://issues.redhat.com/browse/JBTM-3649)
examples-microprofile-lra-cdi-embedded and participant
https://github.com/jbosstm/narayana/pull/2021
this PR depends on https://github.com/jbosstm/quickstart/pull/395

JBTM-3649 examples-microprofile-lra-cdi-embedded and participant

---

rts/lra-examples/coordinator-quarkus/pom.xml
rts/lra-examples/coordinator-quarkus/src/main/resources/application.properties
rts/lra-examples/coordinator-quarkus/src/main/resources/reflection-config.json
rts/lra-examples/lra-coordinator/pom.xml
rts/lra-examples/pom.xml

This PR is complementary to the PR related to https://issues.redhat.com/browse/JBTM-3658
The PR is https://github.com/jbosstm/narayana/pull/2033

JBTM-3658 LRA coordinator quarkus

---

scripts/hudson/quickstart.sh

The quickstarts no longer use narayana-full/target/narayana-full-6.0.0.Final-SNAPSHOT-bin.zip

narayana zip is not used

---

ArjunaJTS/interop/glassfish/step1.sh
ArjunaJTS/standalone/src/main/java/org/jboss/narayana/jta/quickstarts/TransactionExample.java
README.md
STM/vertx/README.adoc
XTS/ssl/README.md
XTS/ssl/xts-over-ssh.sh
jts-atomic-app/README.md
rts/at/undertow/README.md
rts/lra-examples/lra-jwt/README.md
rts/lra-examples/lra-jwt/wildfly/README.md
scripts/hudson/quickstart.bat
scripts/hudson/quickstart.sh
transactionaldriver/transactionaldriver-standalone/README.md
wildfly/setCheckedActionFactoryExample/README.md

https://issues.redhat.com/browse/JBTM-3718
Ensure that the narayana project is following best practices and recommendations in relation to the use of Conscious Language.
The primary change will be the renaming of the main branch to `main`. Also sweep the code base looking for use of terms like master/slave replacing them with primary/secondary.
P.S. jts-distributed-crash-rec quickstart does not existing anymore (https://issues.redhat.com/browse/WFLY-16140)

[JBTM-3718] Conscious Language

---

jta-and-hibernate-standalone/pom.xml
jta-and-hibernate-standalone/src/main/java/org/jboss/narayana/quickstart/jta/EntityManagerFactoryProducer.java
jta-and-hibernate-standalone/src/main/java/org/jboss/narayana/quickstart/jta/QuickstartApplication.java
jta-and-hibernate-standalone/src/main/resources/META-INF/beans.xml
jta-and-hibernate-standalone/src/test/java/org/jboss/narayana/quickstart/jta/TestCase.java
jta-and-hibernate-standalone/src/test/java/org/jboss/narayana/quickstart/jta/TransactionalConnectionProviderTest.java
jta-and-hibernate-standalone/src/test/resources/META-INF/persistence.xml

This PR migrates `jta-and-hibernate-standalone` to jakarta and addresses JBTM-3158

Jbtm 3699 & jbtm 3158

---

XTS/ssl/xts-over-ssh.sh

Addresses [JBTM-3737](https://issues.redhat.com/browse/JBTM-3737)

[JBTM-3737] Replaced rm -rf with rm -r

---

compensating-transactions/mongodb-simple/pom.xml
compensating-transactions/mongodb-simple/src/test/java/org/jboss/narayana/quickstarts/mongodb/simple/BankingServiceTest.java
pom.xml

This PR addresses [JBTM-3742](https://issues.redhat.com/browse/JBTM-3742)

[JBTM-3742] Updated MongoDB quickstart

---

pom.xml
spring/pom.xml
transactionaldriver/pom.xml

https://issues.redhat.com/browse/JBTM-3747

[JBTM-3747] Disable spring quickstarts, transactionaldriver quickstarts

---

pom.xml

Use the latest jakarta native version of the spi

upgrade jboss-transaction-spi

---

ArjunaJTA/object_store/pom.xml
agroal/pom.xml
jta-1_2-standalone/pom.xml
jta-and-hibernate-standalone/pom.xml
pom.xml
rts/at/undertow/pom.xml
rts/lra-examples/cdi-embedded/pom.xml
rts/lra-examples/cdi-participant/pom.xml
rts/lra-examples/coordinator-quarkus/pom.xml
transactionaldriver/transactionaldriver-standalone/pom.xml

JBTM-3779: Move out the test artifacts in narayana-bom
https://issues.redhat.com/browse/JBTM-3779
depends on PR https://github.com/jbosstm/narayana/pull/2138

JBTM-3779: Move out the test artifacts in narayana-bom

---

CODEOWNERS

See discussion in Narayana PR: https://github.com/jbosstm/narayana/pull/2129
and Zulip topic https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/.E2.9C.94.20CONTRIBUTING.2Emd
NO_TESTS

CODEOWNERS removed

---

pom.xml

Issue: https://issues.redhat.com/browse/JBTM-3733
Note: Checkstyle not applied to all the Arjuna code.
(Checkstyle is set to false)
Keeping it on hold as we are still discussing on checkstyle to be applied or no.
(Hold label removed)

[Jbtm 3733]: Implement checkstyle to the Narayana SPI and quickstart modules

---

ArjunaJTA/object_store/pom.xml

https://issues.redhat.com/browse/JBTM-3818

JBTM-3818 Include an SLF4J binder on the classpath

---

tools/download-maven.sh

use https to download maven

---

ArjunaCore/txoj/pom.xml
ArjunaJTA/pom.xml
ArjunaJTA/recovery/pom.xml

BUILD SCRIPT ONLY: Remove WildFly logging dependency from pom.xml

---

ArjunaJTA/jakartaee_transactional_app/README.md
README.md
compensating-transactions/mongodb-simple/README.md
compensating-transactions/non-transactional_resource/README.md
compensating-transactions/travel-agent/README.md
jta-1_2-in-wildfly/README.md
scripts/hudson/quickstart.sh

https://issues.redhat.com/browse/JBTM-3844
This is a work in progress as there are other quickstarts that I presume will need these changes or similar ones
The quickstart.sh has been modified to be usable for this issue.

JBTM-3844 Explain how to obtain a version of WildFly that is built with the expected version of Narayana in it

---

scripts/hudson/quickstart.sh

BUILD SCRIPT ONLY: Comment on the reason for the failure

---

ArjunaJTA/jakartaee_transactional_app/README.md
README.md
compensating-transactions/mongodb-simple/README.md
compensating-transactions/non-transactional_resource/README.md
compensating-transactions/travel-agent/README.md
jta-1_2-in-wildfly/README.md
scripts/hudson/quickstart.sh

Includes an alternative version of https://issues.redhat.com/browse/JBTM-3844 and an (unrelated) small tweak to only delete the Narayana checkout if it's explicitly asked for

Jbtm 3844 download and update

---

ArjunaJTA/jakarta_transaction/pom.xml
ArjunaJTA/object_store/pom.xml
ArjunaJTA/recovery/pom.xml
ArjunaJTS/recovery/pom.xml
ArjunaJTS/standalone/pom.xml
XTS/pom.xml
XTS/ssl/README.md
compensating-transactions/travel-agent/pom.xml
jta-and-hibernate-standalone/pom.xml
pom.xml
rts/at/recovery/recovery1/pom.xml
rts/at/recovery/recovery2/pom.xml
rts/at/service/service1/pom.xml
rts/at/service/service2/pom.xml
rts/at/undertow/pom.xml
rts/lra-examples/lra-jwt/wildfly/client/pom.xml

Update for tag 6.0.2.Final 

---

ArjunaJTA/recovery/pom.xml
XTS/pom.xml
XTS/raw-xts-api-demo/core/pom.xml
XTS/raw-xts-api-demo/ear/pom.xml
XTS/raw-xts-api-demo/pom.xml
XTS/raw-xts-api-demo/test/pom.xml
XTS/raw-xts-api-demo/war/pom.xml
XTS/raw-xts-api-demo/webservices/pom.xml
XTS/wsat-jta-multi_service/pom.xml
compensating-transactions/non-transactional_resource/pom.xml
compensating-transactions/pom.xml
compensating-transactions/travel-agent/pom.xml

There is no accompanying JBTM.
When I build the quickstarts sort pom is adding these changes.
NOTEST

changes made by sortpom

---

ArjunaJTA/jakartaee_transactional_app/README.md
README.md
XTS/raw-xts-api-demo/core/pom.xml
compensating-transactions/mongodb-simple/README.md
compensating-transactions/non-transactional_resource/README.md
compensating-transactions/travel-agent/README.md
compensating-transactions/travel-agent/pom.xml
jta-1_2-in-wildfly/README.md
jta-and-hibernate-standalone/pom.xml
pom.xml
scripts/hudson/quickstart.sh
transactionaldriver/transactionaldriver-standalone/pom.xml
wildfly/commit-markable-resource/pom.xml

This PR includes commits from JBTM-3870 and JBTM-3844.
note: ws-t11 dependency needs the 'api' classifier.

Build 6.0 against JDK 21

---

XTS/raw-xts-api-demo/core/pom.xml
compensating-transactions/travel-agent/pom.xml

This reverts commit a5f64fd7cc97c23317a212619f5fda03e973a900.
https://issues.redhat.com/browse/JBTM-3927

[JBTM-3927] Revert "add needed ws-t11 api dependency"

---

rts/at/jta-service/jpa/pom.xml
rts/lra-examples/lra-jwt/wildfly/client/pom.xml

https://issues.redhat.com/browse/JBTM-3942

JBTM-3942 Migrate to Eclipse implementation of JSON-P

---

ArjunaJTA/jakartaee_transactional_app/pom.xml
ArjunaJTA/pom.xml
ArjunaJTS/interop/resource/pom.xml
ArjunaJTS/interop/test-ejbs/pom.xml
ArjunaJTS/pom.xml
XTS/raw-xts-api-demo/test/pom.xml
XTS/wsat-jta-multi_hop/pom.xml
XTS/wsat-jta-multi_service/pom.xml
agroal/README.md
compensating-transactions/mongodb-simple/pom.xml
compensating-transactions/non-transactional_resource/pom.xml
compensating-transactions/travel-agent/pom.xml
pom.xml
rts/at/pom.xml
rts/at/recovery/recovery2/pom.xml
rts/at/service/service2/pom.xml
rts/lra-examples/cdi-embedded/pom.xml
rts/lra-examples/cdi-participant/pom.xml
rts/lra-examples/lra-jwt/wildfly/pom.xml
rts/lra-examples/pom.xml
rts/lra/flight-service/Dockerfile
rts/lra/hotel-service/Dockerfile
rts/lra/lra-coordinator/Dockerfile
rts/lra/trip-controller/Dockerfile
scripts/hudson/quickstart.sh
spring/narayana-spring-boot/pom.xml
transactionaldriver/transactionaldriver-standalone/README.md

https://issues.redhat.com/browse/JBTM-3947

JBTM-3947 End jdk11 support

---

pom.xml
rts/lra-examples/coordinator-quarkus/pom.xml
rts/lra-examples/lra-jwt/wildfly/lra-coordinator/pom.xml
rts/lra/flight-service/pom.xml
rts/lra/hotel-service/pom.xml
rts/lra/trip-client/pom.xml
rts/lra/trip-controller/pom.xml
scripts/hudson/quickstart.sh

Update the version and the new groupID of the lra artifacts from https://github.com/jbosstm/lra

Jbtm 3947  Move lra component into a new jbosstm project

---

scripts/hudson/quickstart.sh

https://issues.redhat.com/browse/JBTM-3926
this is intended to be tested against WildFly 35.0.0.Final

[JBTM-3926]leftover LRA migrated from rts to lra

---

scripts/hudson/quickstart.sh

BUILD SCRIPT ONLY: Fail if clone of Narayana or LRA fails

---

pom.xml

Update lra version to 1.0.0.Final

Update lra version to 1.0.0.Final

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
dco.txt

Updated to latest CONTRIBUTING.md, CODE_OF_CONDUCT.md and dco.txt from jbosstm/narayana

---

XTS/wsat-jta-multi_hop/pom.xml
jpms/jta/config/pom.xml
jpms/jta/demo/pom.xml
jpms/jta/pom.xml
jpms/jta/recovery/pom.xml
jpms/jta/txuser/pom.xml
jpms/pom.xml
pom.xml

https://issues.redhat.com/browse/JBTM-4009

JBTM-4009 Replace `bom` with `dependency-management`
